_extends: .github

repository:
  name: nucleos-doctrine-extensions
  description: ⚙️ Useful doctrine event hooks.
  homepage: https://nucleos.rocks
  topics: hacktoberfest, library, doctrine, hooks, symfony, symfony-bridge, confirmable, deletable, lifecycle, sortable
