# These settings are synced to GitHub by https://probot.github.io/apps/settings/

_extends: .github

repository:
  name: nucleos-doctrine-extensions
  description: ⚙️ Useful doctrine event hooks.
  homepage: https://nucleos.rocks
  topics: hacktoberfest, library, doctrine, hooks, symfony, symfony-bridge, confirmable, deletable, lifecycle, sortable

branches:
  - name: main
    protection:
      enforce_admins: false
      required_status_checks:
        contexts:
          - "Coding Standards (8)"
          - "Static Code Analysis (8)"
          - "Test (PHP 8, symfony 4.4, lowest)"
          - "Test (PHP 8, symfony 5.3, lowest)"
          - "Test (PHP 8, symfony 4.4, highest)"
          - "Test (PHP 8, symfony 5.3, highest)"
          - "Test (PHP 8.1, symfony 4.4, lowest)"
          - "Test (PHP 8.1, symfony 5.3, lowest)"
          - "Test (PHP 8.1, symfony 4.4, highest)"
          - "Test (PHP 8.1, symfony 5.3, highest)"
          - "Code Coverage (8.1)"
          - "Mutation Tests (8.1)"
        strict: true

      required_pull_request_reviews: null
      restrictions: null
